name: Cypress Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '35 18 * * *' # Runs at 18:35 (6:35 PM) Berlin time

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4 # use the explicit version number
        with:
          command: npm run test

      - name: Uploading artifact
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-execution-report
          path: cypress/reports/html
          retention-days: 30

      # - uses: actions/upload-artifact@v1
        # if: failure()
        # with:
          # name: cypress-screenshots
          # path: cypress/screenshots

      # - uses: actions/upload-artifact@v1
        # if: always()
        # with:
          # name: cypress-videos
          # path: cypress/videos
