name: Cypress Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run 1
        uses: cypress-io/github-action@v4
        with:
          command: npm run test

      - name: Uploading artifact 1
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-execution-report 66
          path: cypress/reports/html
          retention-days: 30

      - name: Checkout number 2 task
        uses: actions/checkout@v4

      - name: Cypress run 2
        uses: cypress-io/github-action@v4
        with:
          command: npm run test

      - name: Uploading artifact 2
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-execution-report 55
          path: cypress/reports/html
          retention-days: 30

      - name: Checkout number 3 task
        uses: actions/checkout@v4

      - name: Cypress run 3
        uses: cypress-io/github-action@v4
        with:
          command: npm run test

      - name: Uploading artifact 3
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-execution-report 77
          path: cypress/reports/html
          retention-days: 30

      - name: Checkout number 4 task
        uses: actions/checkout@v4

      - name: Cypress run 4
        uses: cypress-io/github-action@v4
        with:
          command: npm run test

      - name: Uploading artifact 4
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-execution-report 99
          path: cypress/reports/html
          retention-days: 30
